version: '3.8'

services:
  mysql:
    image: mysql:8.0.29
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lc
    ports:
      - '3306:3306'
    working_dir: /lc
    volumes:
      - lc-mysql:/var/lib/mysql #数据文件
      - lc-mysql:/etc/mysql/conf.d #配置文件
      - lc-mysql:/var/log/mysql #日志文件
      - ./:/lc

volumes:
  lc-mysql: